#ifndef POCL_PRINTF_BUFFER_H
#define POCL_PRINTF_BUFFER_H

// number of bits reserved to flags in the control word
#define PRINTF_BUFFER_CTWORD_FLAG_BITS 6

#define PRINTF_BUFFER_CTWORD_SKIP_FMT_STR 2

#define PRINTF_BUFFER_CTWORD_CHAR_SHORT_PR 4

#define PRINTF_BUFFER_CTWORD_CHAR2_PR 8

#define PRINTF_BUFFER_CTWORD_FLOAT_PR 16

#define PRINTF_BUFFER_CTWORD_BIG_ENDIAN 32

#endif // POCL_PRINTF_BUFFER_H
