#!/bin/bash
#
# run_level0_tests - Runs tests against LevelZero devices.
#
# Copyright (c) 2023 Michal Babej / Intel Finland Oy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

export POCL_BUILDING=1
export POCL_DEVICES="level0"
export IGC_EnableDPEmulation=1
export OverrideDefaultFP64Settings=1
# necessary to workaround issues with llvm-spirv translator
export CL_OFFLINE_COMPILER_DISABLE_OPT=1

if [ -z "$OCL_ICD_VENDORS" ]; then
  export OCL_ICD_VENDORS=$PWD/ocl-vendors
fi
if [ ! -e "$OCL_ICD_VENDORS" ]; then
  echo "Not using OCL_ICD_VENDORS ($OCL_ICD_VENDORS doesn't exist)"
else
  echo "Using OCL_ICD_VENDORS: $OCL_ICD_VENDORS"
fi

ctest -L level0 $@
