#!/bin/bash
# run_tta_tests - Runs tests against the tta device drivers.
#
# Copyright (c) 2021 Michal Babe / Tampere University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

export POCL_BUILDING=1
export POCL_DEVICES=accel

if [ -z "$OCL_ICD_VENDORS" ]; then
  export OCL_ICD_VENDORS=$PWD/ocl-vendors
fi

if [ ! -e "$OCL_ICD_VENDORS" ]; then
  echo "OCL_ICD_VENDORS: $OCL_ICD_VENDORS doesn't exist"
  exit 1
fi

echo "Using OCL_ICD_VENDORS: $OCL_ICD_VENDORS"


declare -a TTATests=("axim_sep" "axim_fused_global_cq" "axim_fused_global_private" "axim_fused_global_cq_private" \
 "relative_sep" "relative_fused_global_cq" "relative_fused_global_private" "relative_fused_global_cq_private")
#declare -a TTATests=("axim_sep")



for val in ${TTATests[@]}; do
  if [ ${PYNQ_AVAILABLE}] then
    export POCL_ACCEL0_PARAMETERS="0xB,$PWD/examples/accel/firmwares/$val,1,2"
  else
    export POCL_ACCEL0_PARAMETERS="0x43C00000,dummy,1,2"
    sudo -E python -c "from pynq import Overlay;Overlay('$PWD/examples/accel/bitstreams/${val}.bit')"
  fi

  echo "Using ACCEL0 params: $POCL_ACCEL0_PARAMETERS"
  ctest -L accel_no_LLVM -R .*i32 $@
done


