#!/bin/bash
# run_vulkan_tests - Runs tests against Vulkan device
#
# Copyright (c) 2021 Michal Babej / Tampere Univ. of Technology
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

export POCL_BUILDING=1
export POCL_DEVICES=vulkan

if [ -z "$OCL_ICD_VENDORS" ]; then
  export OCL_ICD_VENDORS=$PWD/ocl-vendors
fi

if [ ! -e "$OCL_ICD_VENDORS" ]; then
  echo "OCL_ICD_VENDORS: $OCL_ICD_VENDORS doesn't exist"
else
  echo "Using OCL_ICD_VENDORS: $OCL_ICD_VENDORS"
fi

ctest -L vulkan $@
