#!/bin/bash
# run_cpu_tests - Runs tests against CPU device with various options
#
# Copyright (c) 2025 Michal Babej / Tampere University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

SOURCE_DIR=$1
BUILD_DIR=$2
REMOTE_ADDRESS=$3
REMOTE_USER=$4

set -euxo pipefail

if [ ! -d $SOURCE_DIR ] || [ ! -d $BUILD_DIR ]; then
  echo "either $SOURCE_DIR or $BUILD_DIR or both are not directories"
  exit 1
fi

RSYNC_DEST=${REMOTE_USER}@${REMOTE_ADDRESS}

for DDIR in cmake include tests examples tools; do
  rsync -a --delete ${SOURCE_DIR}/$DDIR/ ${RSYNC_DEST}:${SOURCE_DIR}/$DDIR/
done
rsync -a --delete ${BUILD_DIR}/ ${RSYNC_DEST}:${BUILD_DIR}/

ssh ${RSYNC_DEST} "source ~/.bashrc && cd $BUILD_DIR && rm -rf /tmp/POCL_CACHE && mkdir /tmp/POCL_CACHE && ctest --output-on-failure -LE cpu_fail -E test_large_buf -j8"
