---
name: Linux OneAPI tests

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
# at 0:23 UTC every saturday
    - cron: '23 0 * * 6'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'CHANGES'
      - 'COPYING'
      - 'CREDITS'
      - 'LICENSE'
      - 'README.*'
      - 'tools/docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

env:
  CCACHE_BASEDIR: "${{ github.workspace }}"
  CCACHE_DIR: "${{ github.workspace }}/../../../ccache_storage"
  EXAMPLES_DIR: "${{ github.workspace }}/../../../examples"

jobs:
  oneapi_matrix:
    name: LLVM ${{ matrix.llvm }} - oneAPI
    runs-on: [self-hosted, linux, x64, oneapi]
    strategy:
      fail-fast: false
      matrix:
        llvm: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Load Env vars
        id: load-env
        run: |
          cat ${{ github.workspace }}/.github/variables.txt >> $GITHUB_ENV

      - name: CMake
        id: cmake
        run: |
          runCMake() {
            BUILD_FLAGS="-O1 -march=native -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable"
            cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DDEVELOPER_MODE=ON \
            -DENABLE_HOST_CPU_DEVICES=1 -DENABLE_LEVEL0=1 -DSTATIC_LLVM=ON \
            -DCMAKE_BUILD_TYPE=Release "-DCMAKE_C_FLAGS_RELEASE=$BUILD_FLAGS" "-DCMAKE_CXX_FLAGS_RELEASE=$BUILD_FLAGS" \
            -DWITH_LLVM_CONFIG=/usr/bin/llvm-config-${{ matrix.llvm }} -DLLVM_SPIRV=/usr/bin/llvm-spirv-${{ matrix.llvm }} \
            "$@" -B ${{ github.workspace }}/build ${{ github.workspace }}
          }

          rm -rf ${{ github.workspace }}/build
          mkdir ${{ github.workspace }}/build
          mkdir -p ${EXAMPLES_DIR}/build_oneapi
          mkdir -p ${EXAMPLES_DIR}/source
          runCMake "-DENABLE_TESTSUITES=dpcpp-book-samples;oneapi-samples;SYCL_CTS" \
            -DTESTSUITE_SOURCE_BASEDIR=${EXAMPLES_DIR}/source -DTESTSUITE_BASEDIR=${EXAMPLES_DIR}/build_oneapi \
            -DSYCL_CXX_COMPILER=/opt/intel/oneapi/compiler/latest/bin/icpx -DSYCL_LIBDIR=/opt/intel/oneapi/compiler/latest/lib

      - name: Build PoCL
        id: build_pocl
        timeout-minutes: 20
        run: |
          cd ${{ github.workspace }}/build && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh)

      - name: Build Examples
        id: build_examples
        # SYCL_CTS takes long time to build
        timeout-minutes: 180
        run: |
          cd ${{ github.workspace }}/build/examples/dpcpp-book-samples && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh) dpcpp-book-samples
          cd ${{ github.workspace }}/build/examples/oneapi-samples && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh) oneapi-samples
          #cd ${{ github.workspace }}/build/examples/simple-sycl-samples && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh) simple-sycl-samples
          #cd ${{ github.workspace }}/build/examples/intel-compute-samples && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh) intel-compute-samples
          cd ${{ github.workspace }}/build/examples/SYCL_CTS && make -j$(${{ github.workspace }}/.github/scripts/get_cpus.sh) SYCL_CTS

      - name: Run CPU Tests (short)
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        id: ctest_cpu_short
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        timeout-minutes: 40
        run: |
          rm -rf ${{ env.POCL_CACHE_DIR }}
          mkdir ${{ env.POCL_CACHE_DIR }}
          source /opt/intel/oneapi/setvars.sh
          cd ${{ github.workspace }}/build && ${{ github.workspace }}/tools/scripts/run_oneapi_tests_cpu -j4 $CTEST_FLAGS -E 'sycl_cts_test_math_builtin_api|sycl_cts_test_multi_ptr|sycl_cts_test_kernel|sycl_cts_test_kernel_bundle|sycl_cts_test_group_functions'

      - name: Run GPU Tests (short)
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        id: ctest_gpu_short
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        timeout-minutes: 40
        run: |
          rm -rf ${{ env.POCL_CACHE_DIR }}
          mkdir ${{ env.POCL_CACHE_DIR }}
          source /opt/intel/oneapi/setvars.sh
          cd ${{ github.workspace }}/build && ${{ github.workspace }}/tools/scripts/run_oneapi_tests_gpu -j4 $CTEST_FLAGS -E 'sycl_cts_test_math_builtin_api|sycl_cts_test_multi_ptr|sycl_cts_test_kernel|sycl_cts_test_kernel_bundle|sycl_cts_test_group_functions'


      - name: Run CPU Tests (long)
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        id: ctest_cpu_long
        if: ${{ github.event_name == 'schedule' }}
        timeout-minutes: 240
        run: |
          rm -rf ${{ env.POCL_CACHE_DIR }}
          mkdir ${{ env.POCL_CACHE_DIR }}
          source /opt/intel/oneapi/setvars.sh
          cd ${{ github.workspace }}/build && ${{ github.workspace }}/tools/scripts/run_oneapi_tests_cpu -j4 $CTEST_FLAGS

      - name: Run GPU Tests (long)
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        id: ctest_gpu_long
        if: ${{ github.event_name == 'schedule' }}
        timeout-minutes: 240
        run: |
          rm -rf ${{ env.POCL_CACHE_DIR }}
          mkdir ${{ env.POCL_CACHE_DIR }}
          source /opt/intel/oneapi/setvars.sh
          cd ${{ github.workspace }}/build && ${{ github.workspace }}/tools/scripts/run_oneapi_tests_gpu -j4 $CTEST_FLAGS


