---
name: Linux ARM64 test matrix

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'CHANGES'
      - 'COPYING'
      - 'CREDITS'
      - 'LICENSE'
      - 'README.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  arm64_matrix:
    name: LLVM ${{ matrix.llvm }} - ARM64 ${{ matrix.config }}
    runs-on: [self-hosted, linux, arm64, ubuntu]
    # Docker runners have action runner in the $HOME/actions-runner directory
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}/../../../../ccache_storage"
      EXAMPLES_DIR: "${{ github.workspace }}/../../../../examples"
    strategy:
      fail-fast: false
      matrix:
        llvm: [18]
        config: [basic]

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Load Env vars
        id: load-env
        run: |
          cat ${{ github.workspace }}/.github/variables.txt >> $GITHUB_ENV
        shell: bash

      - name: Run CMake
        id: cmake
        run: |
          runCMake() {
            BUILD_FLAGS="-O1 -march=native -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable"
            cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DDEVELOPER_MODE=ON \
            -DCMAKE_BUILD_TYPE=Release "-DCMAKE_C_FLAGS_RELEASE=$BUILD_FLAGS" "-DCMAKE_CXX_FLAGS_RELEASE=$BUILD_FLAGS" \
            -DWITH_LLVM_CONFIG=/opt/LLVM_${{ matrix.llvm }}0/bin/llvm-config \
            "$@" -B ${{ github.workspace }}/../build/arm64 ${{ github.workspace }}
          }

          rm -rf ${{ github.workspace }}/../build/arm64
          mkdir ${{ github.workspace }}/../build/arm64
          runCMake -DENABLE_ICD=1

      - name: Run Build
        id: build
        run: |
          cd ${{ github.workspace }}/../build/arm64 && make -j$(nproc)

      - name: Run Tests
        env:
          POCL_CACHE_DIR: "${{ runner.temp }}/GH_POCL_CACHE"
        id: ctest
        timeout-minutes: 120
        run: |
          rm -rf ${{ env.POCL_CACHE_DIR }}
          mkdir ${{ env.POCL_CACHE_DIR }}
          cd ${{ github.workspace }}/../build/arm64 && ctest -j$(nproc) $CTEST_FLAGS -L internal -E 'test_shuffle_half_'
